name: Build, Push, and Deploy Java App to EC2

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=sha,prefix={{branch}}-,enable={{is_default_branch}}
            type=sha,prefix=tag-,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ github.repository }}:cache
            type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max

  deploy-to-ec2:
    name: Deploy to EC2 via SSH
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2 and Run Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🔧 Installing Docker if not present..."
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
              newgrp docker
              echo "Docker installed"
            else
              echo "Docker already installed"
            fi

            echo "Pulling latest image from GHCR..."
            docker pull ghcr.io/${{ github.repository }}:latest

            echo "Stopping and removing any old container..."
            docker stop myapp || true
            docker rm myapp || true

            echo "Starting new container..."
            docker run -d --name myapp -p 8081:8080 ghcr.io/${{ github.repository }}:latest

            echo "Deployment successful! App is running on port 8081"
